### ISSUE TITLE
Sent Shi Weas NFT from Soonaverse to IOTA with invalid Sigature

### ISSUE THREAD

**Issue by Phyloiota** [buildcore-io/core#2890]
**Describe the bug**
You used an invalid signature to sign a block. This caused my HFT withdrawal to get stuck

**To Reproduce**
see the Transaction

https://explorer.iota.org/mainnet/block/0x95e325e637ce7d90cb42ef46b52e66e73500d0726417eb43e110f59ad8ec9338?tab=Payload

Please issue this transaction with a valid signature

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by adam-635** [comment]
related to https://github.com/soonaverse/app/issues/182

**Comment by GerritoMuc** [comment]
Diverse transaction stuck from my side, due to the invalid signature. Might help identify a rootcause and possible fix @adamunchained. It spans across collections and L1s:
Shimmer:
1. https://explorer.shimmer.network/shimmer/block/0xcf4a873a7b8d4dc984865703ef5e6253968b07010e60880aab8eaf21ef13ee23 (Iotapunk)
2. https://explorer.shimmer.network/shimmer/block/0x4983f38b02b48a9586081e42c71cc30c25f856f835722a3fd9d02e6c020ae298?tab=Payload (Iotapunk Tetris)
3. https://explorer.shimmer.network/shimmer/block/0xeedfc93724b154b6ae6b18aa9aea4c9ddc548d843423ef655889c975dc670011?tab=Payload (Iotapunk 3D)

Iota:
1. https://explorer.iota.org/mainnet/block/0x34d1c21c19950aa2bbef80bc01b51a2f8863b0a2d953843e0e784569317caf2e?tab=Metadata (Munkii)
2. https://explorer.iota.org/mainnet/block/0x60dd9f00a2324bbc290e3510fb1fe4f0bdb88d240cfdd6dca83adc7300751757 (Iotaholic)
